### ISSUE TITLE
Seu projeto esta incompleto

### ISSUE THREAD

**Issue by RomuloFerreiraFreire** [adsTecnologia1/controleDeNegocios#1]
Busquei algo em seu projeto que me ajudasse, mas percebi que ele esta incompleto.
Quando voltara a implementa-lo?

**Comment by adsTecnologia1** [comment]
Poxa meu caro no momento ando meio na correria, mas em breve estaremos implementando novamente este projeto.
Abraço!

**Comment by romuloadsfreire** [comment]
Isso mesmo cara também percebi que esta faltando algo.
Abraço

**Comment by adsTecnologia1** [comment]
Caro @romuloadsfreire  para melhor entender onde pausamos o projeto, recomendo que você faça um clone do projeto e tente entende-lo melhor.
[clique aqui](https://github.com/adsTecnologia1/controleDeNegocios)
